version: "2"

run:
  go: "1.26.3"

output:
  sort-results: true
  print-issued-lines: false

linters:
  enable:
    - nolintlint
    - revive
    - staticcheck
    - bodyclose
    - cyclop
    - dupword
    - errname
    - exhaustive
    - misspell
    - nestif
    - perfsprint
    - prealloc
    - predeclared
    - testifylint
    - unconvert
    - usestdlibvars

linters-settings:
  govet:
    enable:
      - nilness
      - reflectvaluecompare
      - sortslice
      - unusedwrite
      - defers
      - atomic
      - nilfunc
      - printf
      - tests
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
