# This file was generated by GoReleaser. DO NOT EDIT.
cask "bp" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "6ce88f534b282198761dc1ffc684765ccd74a7a455c692f0dcd0b80dfed02a18"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "f6500b58c0bbfc83a3d79f90d26e0018ed12ec0d9ac80eda8bef2b696c7e2cac"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  on_linux do
    on_intel do
      sha256 "71074c84fd8badc803e34c798701179b459e7b3adfb1fe1d10431be964282713"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "34ab37474ff60595e2f8eb1fc43a093403066733a7ef424fe25c2e055ef9773c"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  name "bp"
  desc "A blood pressure journal"
  homepage "https://github.com/roma-glushko/bp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bp --help
  EOS
end
