# This file was generated by GoReleaser. DO NOT EDIT.
cask "bp" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "80fc36bfc1e587370c93230047a2a992fa6ec85fccd1b11c39cd710049f24189"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "fcdf20f842c5dac0ddab7ebdc2bb08100a195c1148beb75a1d835a05ec2f1c54"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fb2d4d5b1cba82f59b5496b454c9d39d24c3e850fb5ccab9479167397c901aa"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "2d7b68db30c30b6e168c6d091fe3e08d9e0db0aa71c22c45ce1a2791ba5cb130"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  name "bp"
  desc "A blood pressure journal"
  homepage "https://github.com/roma-glushko/bp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bp --help
  EOS
end
