# This file was generated by GoReleaser. DO NOT EDIT.
cask "bp" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "b0becdf9528537faba5af3da862777ff48a09a099e04143fd14499140ccd41fc"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "d391a65a6601124c1e58c518ca7e680a0a6960526d915768526b3c2b843ca661"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  on_linux do
    on_intel do
      sha256 "2da367e3aa3064a9266a8db6d5b942a5dee524ce38f00d6a523e942c2bcc0840"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
    on_arm do
      sha256 "b6104f9a80fa2e351e5092206fcf7c8c436d90ff90a79abf85874bfd841b47da"
      url "https://github.com/roma-glushko/bp/releases/download/v#{version}/bp_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/bp/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
    end
  end

  name "bp"
  desc "A blood pressure journal"
  homepage "https://github.com/roma-glushko/bp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    bp --help
  EOS
end
